FROM ubuntu:rolling

RUN apt-get update -y \
    && apt-get install python3 python3-pip python3-venv -y \ 
    && rm -rf /var/lib/apt/lists/*
# Install dependencies:
WORKDIR /application
COPY ./src/requirements.txt /application
RUN python3 -m venv myenv  \
    && . ./myenv/bin/activate \
    && pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu \
    && pip install sentencepiece

RUN . ./myenv/bin/activate && pip3 install -r requirements.txt    
ADD .env /application/
COPY ./src/ /application

#CMD ["sleep","500"]
CMD ["/bin/bash", "-c", ". ./myenv/bin/activate && flask run --host=0.0.0.0"]

